version: '2'
services:
  redis:
    image: redis
    networks:
      - app
    restart: always
  app:
    build: .
    networks:
      - app
    depends_on:
      - redis
    restart: always
  proxy:
    build: proxy
    volumes:
      - /srv/pgsql/cache/ztf-products-dev:/cache
    networks:
      - app
      - proxy
    environment:
      VIRTUAL_HOST: ztf-dev.snad.space
      HTTPS_METHOD: noredirect
      DYNDNS_HOST: ztf-dev.snad.space
      LETSENCRYPT_HOST: ztf-dev.snad.space
      LETSENCRYPT_EMAIL: ztf-dev@homb.it
    depends_on:
      - app
    restart: always
  proxy-cache-filler:
    build: proxy-cache-filler
    networks:
      - app
    depends_on:
      - proxy
    restart: on-failure

networks:
  app:
  proxy:
    external:
      name: proxy
