version: '2'
services:
   web:
     build: .
     networks:
       - proxy
     environment:
       VIRTUAL_HOST: ztf.homb.it,ztf.snad.space
       DYNDNS_HOST: ztf.homb.it,ztf.snad.space
       LETSENCRYPT_HOST: ztf.homb.it,ztf.snad.space
       LETSENCRYPT_EMAIL: ztf@homb.it
     restart: always

networks:
  proxy:
    external:
      name: proxy
