version: '2'
services:
  redis:
    image: redis
    networks:
      - app
    restart: always

  ztf-web-viewer-app:
    build: .
    environment:
      - VIRTUAL_HOST=ztf.snad.space
      - DYNDNS_HOST=ztf.snad.space
      - LETSENCRYPT_HOST=ztf.snad.space
      - LETSENCRYPT_EMAIL=letsencrypt@snad.space
    networks:
      - app
      - proxy
    depends_on:
      - redis
    restart: always

networks:
  app:
  proxy:
    external:
      name: proxy
