version: '2'
services:
   redis:
     image: redis
     networks:
       - app
     restart: always
   web:
     build: .
     networks:
       - app
       - proxy
     environment:
       VIRTUAL_HOST: ztf-dev.snad.space
       DYNDNS_HOST: ztf-dev.snad.space
       LETSENCRYPT_HOST: ztf-dev.snad.space
       LETSENCRYPT_EMAIL: ztf-dev@homb.it
     depends_on:
       - redis
     restart: always

networks:
  app:
  proxy:
    external:
      name: proxy
