version: '2'
services:
  redis:
    image: redis
    networks:
      - app
    restart: always
  ztf-web-viewer-app:
    build: .
    networks:
      - app
    depends_on:
      - redis
    restart: always
  ztf-web-viewer-proxy:
    build: proxy
    volumes:
      - /srv/pgsql/cache/ztf-products:/cache
    networks:
      - app
      - proxy
    environment:
      VIRTUAL_HOST: ztf.snad.space
      DYNDNS_HOST: ztf.snad.space
      LETSENCRYPT_HOST: ztf.snad.space
      LETSENCRYPT_EMAIL: ztf@snad.space
    depends_on:
      - ztf-web-viewer-app
    restart: always
  proxy-cache-filler:
    build: proxy-cache-filler
    networks:
      - app
    depends_on:
      - ztf-web-viewer-proxy
    restart: on-failure

networks:
  app:
  proxy:
    external:
      name: proxy
