version: '2'
services:
  redis:
    image: redis
    networks:
      - app
    restart: always

  ztf-web-viewer-app:
    build: .
    environment:
      - LC_API_URL=http://db.ztf.snad.space
      - VIRTUAL_HOST=ztf-dev.snad.space
      - HTTPS_METHOD=noredirect
      - DYNDNS_HOST=ztf-dev.snad.space
      - LETSENCRYPT_HOST=ztf-dev.snad.space
      - LETSENCRYPT_EMAIL=ztf-dev@snad.space
    networks:
      - app
      - proxy
    depends_on:
      - redis
    restart: always

networks:
  app:
  proxy:
    external:
      name: proxy
